config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'user_relations/show'
  get 'user_relations/create'
  get 'user_relations/destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  
  resources :users, except:[:new, :create] do
    member do
      get :following, :followers
    end
    resources :events
    resources :groups do
      resources :group_user_relationships, only:[:create, :destroy, :show]
    end
  end
  
  get '/participating', to: 'groups#participating'
  get '/invited', to: 'groups#invited'
  
  resources :relationships, only:[:create, :destroy, :show]
  resources :user_relations, only:[:create, :destroy, :show]
  
  get 'redirect', to: 'google_calendars#redirect', as: 'redirect'
  get 'callback', to: 'google_calendars#callback', as: 'callback'
  get '/list_all', to: 'google_calendars#list_all', as: 'list_all'
  get '/list_part', to: 'google_calendars#list_part', as: 'list_part'
  
  delete '/deleteevent', to: 'events#delete_event'
  post '/createevent', to: 'events#create_event'
  patch '/editevent', to: 'events#edit_event'
  
  resources :account_activations, only:[:edit] 
  resources :password_resets, only:[:new, :edit, :update, :create]
  
  
  root 'static_pages#home'
end

app/models/group.rb
class Group < ApplicationRecord
    belongs_to :user
    has_many :passive_relationships, class_name: 'Relationship',
                                     foreign_key: 'followed_id',
                                     dependent: :destroy
    has_many :followers, through: :passive_relationships    
    
    has_many :active_group_user_relationships, class_name: 'GroupUserRelationship',
                                    foreign_key: 'follower_id',
                                    dependent: :destroy
    has_many :followeds, through: :active_group_user_relationships
    
    validates :title, presence: true
    validates :starttime, presence: true
    validates :endtime, presence: true
    validates :timelength, presence: true
    def follow(other_user)
        active_group_user_relationships.create(followed_id: other_user.id)
    end
    
    def unfollow(other_user)
        active_group_user_relationships.find_by(followed_id: other_user.id).destroy
    end
    
    def following?(other_user)
        followeds.include?(other_user)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @groups = @user.groups
  end

  #記録用が多いので後で消す
  def show
    @users = current_user.user_followeds.search(params[:search])
    @user = User.find(params[:user_id])
    @group = @user.groups.find(params[:id])
    @event_count = 0
    @convinient_event = []
    @inconvinient_event = []
    @follower_count = 0
    @time_count = 0
    @follower_count_array = []
    @convinient_time_array = []
    @time_number = ((@group.endtime - @group.starttime) / 3600 ).floor - 1
    @eventforward = []
    @eventback = []
    
    for num_day in 0..6
    for num in Range.new(24*num_day,24*num_day + @time_number)
      @group.followers.each do |follower|
        if follower.events.any?
          follower.events.each do |event|
            num_next = num + 1
            if event.end < @group.starttime.since(num.hour) || @group.starttime.since(num_next.hour) < event.start
              @event_count += 1
              @convinient_event.push(event.title)
              @eventforward.push(event.title)
              @eventforward.push(event.start)
              @eventforward.push(event.end)
              @eventforward.push(@group.starttime.since(num.hour))
            else
              @inconvinient_event.push(event.title)
            end
          end
          if @event_count == follower.events.count
            @follower_count += 1
          end
          @event_count = 0
        else
          @follower_count += 1
        end
      end
      if @follower_count == @group.followers.count
        @convinient_time_array.push(num)
      else
        @time_count += 1
      end
      @follower_count = 0
    end
    end
    
    
    
    i = @convinient_time_array[0]
    @complete_array = @convinient_time_array.inject([@convinient_time_array[0]]) do |r, v|
      if v != i
        if i - r.last >= 2
         r << "to #{i - 1}"
        end
        r << v
        i = v
      end
      i += 1
      r
    end
    
    @completed_time_array = []
    @position_start = 0
    @position_end = 0
    @number_start = 0
    @number_end = 0
    
  end
  
  def participating
    @groups = current_user.followeds
  end
  
  def invited
    @groups = current_user.followers
  end

  def new
    @group = current_user.groups.build
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      current_user.follow(@group)
    end
    respond_to do |format|
      if @group.save
        logger.debug("save成功")
        format.js { @status = 'success' }
      else
        logger.debug("save失敗")
        format.js { @status = 'fail' }
      end
    end
  end

  def destroy
  end
  
    private
      
      def group_params
        params.require(:group).permit(:title, :content, :starttime, :endtime, :timelength)
      end
      
      
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
    <div><%= hidden_field_tag :followed_id, @group.id %></div>
    <%= f.submit "Join", class: "btn btn-primary" %>
<% end %>

app/views/groups/_follow_form.html.erb
<div id="follow_form">
  <% if current_user.following?(@group) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
</div>

app/views/groups/_new.html.erb
<!-- group作成のパーシャル -->
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h2 class="modal-title">create group</h2>
        </div>
        <div class="modal-body">
            <div class = 'container-fluid'>
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <%= form_for(@group, url: user_groups_path, remote: true) do |f| %>
                            <%= f.label :title %>
                            <%= f.text_field :title %>

                            <%= f.label :content %>
                            <%= f.text_area :content %>

                            <%= f.label :starttime %>
                            <div class='input-group date datetimepicker-form' style="margin-bottom: 10px;">
                              <%= f.text_field :starttime, class: 'form-control' %>
                              <span class="input-group-addon">
                                <span class="fa fa-calendar"></span>
                              </span>
                            </div>

                            <%= f.label :endtime %>
                            <div class='input-group date datetimepicker-form' style="margin-bottom: 10px;">
                              <%= f.text_field :endtime, class: 'form-control' %>
                              <span class="input-group-addon">
                                <span class="fa fa-calendar"></span>
                              </span>
                            </div>

                            <%= f.label :timelength %>
                            <%= f.number_field :timelength %>

                            <%= f.submit "Create group", class: "btn btn-primary" %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">閉じる</button>
        </div>
    </div>
</div>

app/views/groups/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @group.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "exit", class: "btn btn-primary" %>
<% end %>

app/views/groups/_user.html.erb
<ul>
    <div class="underline" style="border-bottom: 1px solid #808080; margin-bottom:10px;"></div>
    <% @group.followers.each do |user| %>
        <li>
            <div class="inline-block user-name"><%= user.name %></div>
            <div class="follow_form float-right">
                <% if current_user.following?(user) %>
                    <%= form_for(current_user.active_user_relations.find_by(user_followed_id: user.id),
                                                                            html: { method: :delete }) do |f| %>
                    <%= f.submit "unfollow", class: "btn btn-primary" %>
                    <% end %>
                <% else %>
                    <%= form_for(current_user.active_user_relations.build) do |f| %>
                        <div><%= hidden_field_tag :user_followed_id, user.id %></div>
                        <%= f.submit "follow", class: "btn btn-primary"  %>
                    <% end %>
                <% end %>
            </div>
                <button class="inline-block btn btn-primary float-right">invite</button>
            <% end %>
            <div class="underline" style="border-bottom: 1px solid #808080; margin-top:10px;"></div>
        </li>
    <% end %>
</ul>

app/views/groups/create.js.erb
$("#form-modal").modal("hide")
<% if @status == 'success' %>
    console.log("success!")
    $("#success-modal").modal("show")
<% elsif @status == 'fail' %>
    console.log("fail!")
    $("#fail-modal").modal("show")
<% end %>

app/views/groups/index.html.erb
<!-- group#indexいらないかも -->
<div class="container">
    
    <h1>Group</h1>
    
    <ul class="nav nav-tabs">
        <li class="nav-item"><%= link_to "Participating groups", participating_path, class: "active" %></li>
        <li class="nav-item"><%= link_to "Invited groups", invited_path %></li>
        <!-- all groupsは後で消す。自分で作ったgroupをフォローする仕組みにしたら -->
        <li class="nav-item active"><%= link_to "All groups", user_groups_path(user_id: current_user.id) %></li>
    </ul>
    
    <h2>All groups</h2>
    <% if !@groups.empty? %>
        <ul>
            <% @groups.each do |group| %>
                <li><%= link_to group.title, user_group_path(@user.id, group) %></li>
            <% end %>
        </ul>
    <% else %>
        <div class="#">グループはありません</div>
    <% end %> 

    
</div>

app/views/groups/invited.html.erb
<div class="container">
    
    <h1>Group</h1>
    
    <ul class="nav nav-tabs">
        <li class="nav-item"><%= link_to "Participating groups", participating_path, class: "active" %></li>
        <li class="nav-item active"><%= link_to "Invited groups", invited_path %></li>
        <!-- all groupsは後で消す。自分で作ったgroupをフォローする仕組みにしたら -->
        <li class="nav-item"><%= link_to "All groups", user_groups_path(user_id: current_user.id) %></li>
    </ul>
    
    <h2>Invited groups</h2>
    <% if !@groups.empty? %>
        <ul>
            <% @groups.each do |group| %>
                <li><%= link_to group.title, user_group_path(current_user.id, group) %></li>
            <% end %>
        </ul>
    <% else %>
        <div class="#">招待中のグループはありません</div>
    <% end %>    
    
    
</div>

app/views/groups/new.html.erb
<h1>Groups#new</h1>
<p>Find me in app/views/groups/new.html.erb</p>

app/views/groups/new.js.erb
console.log("たしかにgroups/new.js.erbが呼ばれました")
$("#form-modal").html("<%= escape_javascript(render 'new') %>")
$("#form-modal").modal("show")
console.log("たしかにgroups/new.js.erbが呼ばれました")
$("#form-modal").html("<%= escape_javascript(render 'new') %>")
$("#form-modal").modal("show")
$('.datepicker-form').datetimepicker({
  format : "YYYY/MM/DD",
  icons: {
    previous: "fa fa-arrow-left",
    next: "fa fa-arrow-right"
  }
});
$('.datetimepicker-form').datetimepicker({
  format : "YYYY/MM/DD HH:mm",
  icons: {
    time: "fa fa-clock-o",
    date: "fa fa-calendar",
    up: "fa fa-arrow-up",
    down: "fa fa-arrow-down",
    previous: "fa fa-arrow-left",
    next: "fa fa-arrow-right"
  }
});
$('.datepicker-form').focus(function(){
  $('.datepicker-dropdown').css("z-index", "1060");
});

app/views/groups/participating.html.erb
<div class="container">
    
    <h1>Group</h1>
    
    <ul class="nav nav-tabs">
        <li class="nav-item active"><%= link_to "Participating groups", participating_path, class: "active" %></li>
        <li class="nav-item"><%= link_to "Invited groups", invited_path %></li>
        <!-- all groupsは後で消す。自分で作ったgroupをフォローする仕組みにしたら -->
        <li class="nav-item"><%= link_to "All groups", user_groups_path(user_id: current_user.id) %></li>
    </ul>
    
    <h2>Participating groups</h2>
    <% if !@groups.empty? %>
        <ul>
            <% @groups.each do |group| %>
                <li><%= link_to group.title, user_group_path(current_user.id, group) %></li>
            <% end %>
        </ul>
    <% else %>
        <div class="#">参加中のグループはありません</div>
    <% end %>
    
</div>

app/views/groups/show.html.erb
<% provide(:title, @group.title) %>

<div class = 'container'>
    
    <h1><%= @group.title %></h1>
    <% if logged_in? %>
        <div class = "follow_form inline-block-nm">
            <%= render 'follow_form' %>
        </div>
        <button class="btn btn-primary inline-block-nm">招待する</button>
    <% elsif %>
        <button class="btn btn-primary inline-block-nm">　ログインして利用する</button>
        <button class="btn btn-primary inline-block-nm">登録する</button>
        <button class="btn btn-primary inline-block-nm">登録せずに利用する</button>
    <% end %>
        <button class="btn btn-primary inline-block-nm">linkを送る</button> 
        
    <div class="row" style="margin-bottom: 100px;">
        <% if !@group.content.empty? %>
            <div class = "col-md-6">
                <h2>description</h2>
                    <div class="">
                        <%= @group.content %>
                    </div>
            </div>
        <% end %>
        
    
        <div class = "col-md-6">
            
            <!-- 参加している人数に合わせて条件分岐 -->
            
                <div class = "schedule">
                    <% if @group.followers.any? %>
                        <h2>schedule</h2>
                        <h3>都合のいい日程</h3>
                            <% if @time_count == @time_number + 1 %>
                                <p>ありませんでした。</p>
                            <% else %>
            <% if @complete_array.count == 1 && @convinient_time_array.count > 1 %>
                <% @number_start = @convinient_time_array[0] %>
                <% @number_end = @convinient_time_array[-1] + 1 %>
                <% if @number_end - @number_start >= @group.timelength %>
                <p><%= @group.starttime.since(@number_start.hour) %>から<%= @group.starttime.since(@number_end.hour) %>まで</p>
                <% else %>
                <p>時間があいませんでした。</p>
                <% end %>
            <% elsif @complete_array.count > 1 && @complete_array[-1] != @convinient_time_array[-1] %>
                <% @complete_array_saved = @complete_array %>
                <ul>
                <% while @complete_array.index {|item| item =~ /^t/ } do %>
                    <% @position_end = @complete_array.index {|item| item =~ /^t/ } %>
                    <% @number_end = @complete_array[@position_end].delete("to").to_i + 1 %>
                    <% @complete_array.delete_at(@position_end) %>
                    <% @position_start = @position_end - 1 %>
                    <% @number_start = @complete_array[@position_start] %>
                    <% if @number_end - @number_start >= @group.timelength %>
                    <li><%= @group.starttime.since(@number_start.hour) %>から<%= @group.starttime.since(@number_end.hour) %>まで</li>
                    <% else %>
                    <p>時間があいませんでした。</p>
                    <% end %>
                <% end %>
                    <% @number_start = @complete_array_saved[-1] %>
                    <% @number_end = @convinient_time_array[-1] + 1 %>
                    <% if @number_end - @number_start >= @group.timelength %>
                    <li><%= @group.starttime.since(@number_start.hour) %>から<%= @group.starttime.since(@number_end.hour) %>まで</li>
                    <% else %>
                    <p>時間があいませんでした。</p>
                    <% end %>
                </ul>
            <% else %>
                <ul>
                <% while @complete_array.index {|item| item =~ /^t/ } do %>
                    <% @position_end = @complete_array.index {|item| item =~ /^t/ } %>
                    <% @number_end = @complete_array[@position].delete("to").to_i + 1 %>
                    <% complete_array.delete_at(@position_end) %>
                    <% @position_start = @position_end - 1 %>
                    <% @number_start = @complete_array[@position_start] %>
                    <% if @number_end - @number_start >= @group.timelength %>
                    <li><%= @group.starttime.since(@number_start.hour) %>から<%= @group.starttime.since(@number_end.hour) %>まで</li>
                    <% else %>
                    <p>時間があいませんでした。</p>
                    <% end %>
                <% end %>
                </ul>
            <% end %>
        <% end %>
        
        <p>timecount: <%= @time_count %></p>
        <p>convinient_time_array: <%= @convinient_time_array %></p>
        <p>complete_array: <%= @complete_array %></p>
        <p>convinient_event: <%= @convinient_event %></p>
        <p>inconvinient_event: <%= @inconvinient_event %></p>
        <p>starttime: <%= @group.starttime %></p>
        <p>endtime: <%= @group.endtime %></p>

        
    <% end %>
    </div>
        </div>
    
            
    </div>
    
    <div class="row">
        <div class="col-md-6">
            <h2>グループのメンバー</h2>
                <div class = "participants">
                    <% if @group.followers.any? %>
                        <%= render 'user' %>
                    <% else %>
                        <p>まだメンバーがいません。</p>
                    <% end %>
                    <h3>招待中</h3>
                        <div class="inviting">
                            <!-- 招待中の処理（ユーザーがinvitationを送る形 ) -->
                        </div>
                </div>
        </div>        
    </div>    




</div>