config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'user_relations/show'
  get 'user_relations/create'
  get 'user_relations/destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  
  resources :users, except:[:new, :create] do
    member do
      get :following, :followers
    end
    resources :events
    resources :groups do
      resources :group_user_relationships, only:[:create, :destroy, :show]
    end
  end
  
  get '/participating', to: 'groups#participating'
  get '/invited', to: 'groups#invited'
  
  resources :relationships, only:[:create, :destroy, :show]
  resources :user_relations, only:[:create, :destroy, :show]
  
  get 'redirect', to: 'google_calendars#redirect', as: 'redirect'
  get 'callback', to: 'google_calendars#callback', as: 'callback'
  get '/list_all', to: 'google_calendars#list_all', as: 'list_all'
  get '/list_part', to: 'google_calendars#list_part', as: 'list_part'
  
  delete '/deleteevent', to: 'events#delete_event'
  post '/createevent', to: 'events#create_event'
  patch '/editevent', to: 'events#edit_event'
  
  resources :account_activations, only:[:edit] 
  resources :password_resets, only:[:new, :edit, :update, :create]
  
  
  root 'static_pages#home'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :start, presence: true
  validates :end, presence: true
  validates :user_id, presence: true
  
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def show
  end
  
  def new
    @event = current_user.events.build
    character = "abcdefghijklmnopqrstuv0123456789"
    character_length = character.length - 1
    @calendar_id = ''
    25.times {
      i = rand(0..character_length)
      str = character[i]
      @calendar_id << str
    }
    logger.debug(@calendar_id)
  end

  def index
    @user = User.find(params[:user_id])
    @events = @user.events
    if @user == current_user
      render json: @events
    else
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
  
  #google calendarにもつっこまないといけない
  #fullcalendarにも?
  def create
    @event = current_user.events.build(event_params)
    if @event.save
      google_calendar = current_user.google_calendars.order(:id).first
      refresh_token = google_calendar.refresh_token
      client = Signet::OAuth2::Client.new(client_options)
      client.update!(refresh_token: refresh_token)
      response = client.fetch_access_token!
      session[:authorization] = response
      google_calendar_event = Google::Apis::CalendarV3::Event.new(summary: @event.title,
                                                                  start: {date_time: @event.start.strftime("%Y-%m-%dT%H:%M:%S+09:00")}, 
                                                                  end: {date_time: @event.end.strftime("%Y-%m-%dT%H:%M:%S+09:00")},  
                                                                  id: @event.calendar_id)
      service = Google::Apis::CalendarV3::CalendarService.new
      service.authorization = client
      service.insert_event("primary", google_calendar_event)                                                            
    end
    respond_to do |format|
      if @event.save
        logger.debug("save成功")
        format.js { @status = 'success' }
      else
        logger.debug("save失敗")
        format.js { @status = 'fail' }
      end
    end
  end


  def destroy
  end
  
  def delete_event
    google_calendar = current_user.google_calendars.order(:id).first
    refresh_token = google_calendar.refresh_token
    client = Signet::OAuth2::Client.new(client_options)
    client.update!(refresh_token: refresh_token)
    response = client.fetch_access_token!
    session[:authorization] = response
    logger.debug("responseは#{response}")
    #idはrailsのeventのid、calendar_idはgooglecalendarのeventのid
    event = current_user.events.find_by(params[:id])
    if !event.calendar_id.nil?
      #calendar_idだけ先にとっておく
      calendar_id = event.calendar_id
      logger.debug("calendar_idは#{calendar_id}")
      #google calendarでも消す
      logger.debug("clientは#{client}")
      service = Google::Apis::CalendarV3::CalendarService.new
      logger.debug("serviceは#{service}")
      service.authorization = client
      logger.debug("authorization完了")
      service.delete_event('primary', calendar_id)
      logger.debug("google_calendarから消しました")
    end
    logger.debug("event_idは#{params[:id]}")
    #DBから消す
    current_user.events.find(params[:id]).destroy
    logger.debug("DBから消しました")
  rescue Google::Apis::ClientError
    logger.debug("いつものエラーです")
    current_user.events.find(params[:id]).destroy
    logger.debug("DBから消しました")
  end
  
  def create_event
    google_calendar = current_user.google_calendars.order(:id).first
    refresh_token = google_calendar.refresh_token
    client = Signet::OAuth2::Client.new(client_options)
    client.update!(refresh_token: refresh_token)
    response = client.fetch_access_token!
    session[:authorization] = response
    event = current_user.events.build
    event.attributes = {
      title: params[:title],
      start: params[:start],
      end: params[:end],
      calendar_id: params[:calendar_id]
    }
    logger.debug("calendar_idは#{event.calendar_id}")
    google_calendar_event = Google::Apis::CalendarV3::Event.new(summary: event.title,
                                                                start: {date_time: event.start.strftime("%Y-%m-%dT%H:%M:%S+09:00")},
                                                                end: {date_time: event.end.strftime("%Y-%m-%dT%H:%M:%S+09:00")},
                                                                id: event.calendar_id)
    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client
    service.insert_event("primary", google_calendar_event)
    event.save
  end
  
  def edit_event
    starttime = params[:start] + "+09:00"
    endtime = params[:end] + "+09:00"
    logger.debug("startの時間は#{starttime}")
    logger.debug("startの時間は#{endtime}")
    #まずrailsのDBを編集
    event = current_user.events.find(params[:id])
    logger.debug("eventは#{event.title}")
    if event.update(start: starttime,
                    end: endtime)
       logger.debug("railsのDBでupdate")
    end
    #google_calenarでのupdate
    google_calendar = current_user.google_calendars.order(:id).first
    refresh_token = google_calendar.refresh_token
    client = Signet::OAuth2::Client.new(client_options)
    client.update!(refresh_token: refresh_token)
    response = client.fetch_access_token!
    session[:authorization] = response
    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client
    calendar_id = event.calendar_id
    google_calendar_event = service.get_event('primary', calendar_id)
    google_calendar_event.start.date_time = starttime
    google_calendar_event.end.date_time = endtime
    service.update_event('primary', calendar_id, google_calendar_event)
  end
  
    private
      def event_params 
        params.require(:event).permit(:title, :start, :end, :calendar_id)    
      end
      
      def client_options
        {          
        client_id: Rails.application.secrets.google_client_id,
        client_secret: Rails.application.secrets.google_client_secret,
        authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
        token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
        scope: Google::Apis::CalendarV3::AUTH_CALENDAR,
        redirect_uri: callback_url
        }
      end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_new.html.erb
<!-- event作成のパーシャル -->
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h2 class="modal-title">create event</h2>
        </div>
        <div class="modal-body">
            <div class = 'container-fluid'>
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <%= form_for(@event, url: user_events_path(user_id: current_user.id), remote: true) do |f| %>
                            <%= f.label :title %>
                            <%= f.text_field :title %>


                            <%= f.label :start %>
                            <div class='input-group date datetimepicker-form' style="margin-bottom: 10px;">
                              <%= f.text_field :start, class: 'form-control' %>
                              <span class="input-group-addon">
                                <span class="fa fa-calendar"></span>
                              </span>
                            </div>


                            <%= f.label :end %>
                            <div class='input-group date datetimepicker-form' style="margin-bottom: 10px;">
                              <%= f.text_field :end, class: 'form-control' %>
                              <span class="input-group-addon">
                                <span class="fa fa-calendar"></span>
                              </span>
                            </div>

                            <%= f.hidden_field :calendar_id, value: @calendar_id %>

                            <%= f.submit "Create event", class: "btn btn-primary" %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">閉じる</button>
        </div>
    </div>
</div>

app/views/events/create.js.erb
<% logger.debug("statusは#{@status}") %>
$("#form-modal").modal("hide")
<% if @status == 'success' %>
    console.log("success!")
    $("#success-modal").modal("show")
<% elsif @status == 'fail' %>
    console.log("fail!")
    $("#fail-modal").modal("show")
<% end %>

app/views/events/index.html.erb
<% if current_user == @user %>
<%= render json: @events %>
<% else %>
<p>ログインしてください</p>
<% end %>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/events/new.js.erb
console.log("たしかにevents/new.js.erbが呼ばれました")
$("#form-modal").html("<%= escape_javascript(render 'new') %>")
$("#form-modal").modal("show")
console.log("たしかにevents/new.js.erbが呼ばれました")
$("#form-modal").html("<%= escape_javascript(render 'new') %>")
$("#form-modal").modal("show")
$('.datepicker-form').datetimepicker({
  format : "YYYY/MM/DD",
  icons: {
    previous: "fa fa-arrow-left",
    next: "fa fa-arrow-right"
  }
});
$('.datetimepicker-form').datetimepicker({
  format : "YYYY/MM/DD HH:mm",
  icons: {
    time: "fa fa-clock-o",
    date: "fa fa-calendar",
    up: "fa fa-arrow-up",
    down: "fa fa-arrow-down",
    previous: "fa fa-arrow-left",
    next: "fa fa-arrow-right"
  }
});
$('.datepicker-form').focus(function(){
  $('.datepicker-dropdown').css("z-index", "1060");
});

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>