config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'user_relations/show'
  get 'user_relations/create'
  get 'user_relations/destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  
  resources :users, except:[:new, :create] do
    member do
      get :following, :followers
    end
    resources :events
    resources :groups do
      resources :group_user_relationships, only:[:create, :destroy, :show]
    end
  end
  
  get '/participating', to: 'groups#participating'
  get '/invited', to: 'groups#invited'
  
  resources :relationships, only:[:create, :destroy, :show]
  resources :user_relations, only:[:create, :destroy, :show]
  
  get 'redirect', to: 'google_calendars#redirect', as: 'redirect'
  get 'callback', to: 'google_calendars#callback', as: 'callback'
  get '/list_all', to: 'google_calendars#list_all', as: 'list_all'
  get '/list_part', to: 'google_calendars#list_part', as: 'list_part'
  
  delete '/deleteevent', to: 'events#delete_event'
  post '/createevent', to: 'events#create_event'
  patch '/editevent', to: 'events#edit_event'
  
  resources :account_activations, only:[:edit] 
  resources :password_resets, only:[:new, :edit, :update, :create]
  
  
  root 'static_pages#home'
end

app/views/layouts/_footer.html.erb
<% if false %>

<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <div class="navbar-header">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "calare", root_path, id: "logo" %></li>
        </ul>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="gnavi" class="collapse navbar-collapse">
        
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <% if current_user.google_calendars.empty? %>
              <li><%= link_to "google calendarと連携する", redirect_path %></li>
            <% end %> 
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                グループ <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "参加中のグループ", participating_path %></li>
                <li><%= link_to "招待されているグループ", invited_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                ユーザー <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "フォロー中のユーザー", following_user_path(current_user.id) %></li>
                <li><%= link_to "フォローされているユーザー", followers_user_path(current_user.id) %></li>
                <li><%= link_to "ユーザーを探す", users_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "My page", user_path(current_user.id) %></li>
                <li><%= link_to "Settings", edit_user_path(current_user.id) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Log in", login_path %></li>
            <li><%= link_to "Sign up", signup_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    
      <% flash.each do |message_type, message| %>
      <div class = "alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      <!-- ajaxでjs.erbを呼ぶためのリンク -->
      <!-- アイコンは変更する -->
      <% if logged_in? && !current_page?(controller: 'static_pages', action: 'home') %>
        <%= link_to new_user_group_path(user_id: current_user.id), class: "create-button create-group-button", remote: true do %>
          <%= fa_icon("users 3x", class: "scale black") %>
        <% end %>
        <%= link_to new_user_event_path(user_id: current_user.id), class: "create-button create-event-button", remote: true do %>
          <%= fa_icon("calendar-plus-o 3x", class: "scale black") %>
        <% end %>
      <% end %>
      
      <%= yield %>
      
      <!-- ここにmodelのタグを表示 -->
      <div id="form-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
      
      <!-- 成功or失敗のモーダル -->
      <%= render 'shared/modal' %>
      
      
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    
  </body>
</html>